services:
  reservation-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation-api
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - reservation-network

networks:
  reservation-network:
    driver: bridge
